create table public.groups (
  id bigint generated by default as identity not null,
  name text not null default ''::text,
  constraint groups_pkey primary key (id),
  constraint groups_name_key unique (name)
) TABLESPACE pg_default;

create table public.bots (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  commit_link text null,
  name text not null,
  "group" bigint not null,
  activated boolean not null default true,
  constraint bots_pkey primary key (id),
  constraint bots_group_name_key unique ("group", name),
  constraint bots_group_fkey foreign KEY ("group") references groups (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.games (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  bot_1 bigint not null,
  bot_2 bigint not null,
  moves text not null default ''::text,
  winner smallint not null default '0'::smallint,
  constraint games_pkey primary key (id),
  constraint games_bot_1_fkey foreign KEY (bot_1) references bots (id) on update CASCADE on delete CASCADE,
  constraint games_bot_2_fkey foreign KEY (bot_2) references bots (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.waitings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  bot bigint null,
  constraint waitings_pkey primary key (id),
  constraint waitings_bot_fkey foreign KEY (bot) references bots (id)
) TABLESPACE pg_default;